// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzRe-GY16SLd4ZoF5b_nW38Hfs0XGSmHE',
    appId: '1:100510560960:web:495988ba14e3681231b325',
    messagingSenderId: '100510560960',
    projectId: 'dbpilot-feb6e',
    authDomain: 'dbpilot-feb6e.firebaseapp.com',
    storageBucket: 'dbpilot-feb6e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe9cq-hU4kWxu9oRh7RIwazbmSt0Z0tqM',
    appId: '1:100510560960:android:23f695faf0ec200531b325',
    messagingSenderId: '100510560960',
    projectId: 'dbpilot-feb6e',
    storageBucket: 'dbpilot-feb6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgT-1NyY2dFXyaz3CeruEkFSY9wcu0Odg',
    appId: '1:100510560960:ios:b42c60bd826046d631b325',
    messagingSenderId: '100510560960',
    projectId: 'dbpilot-feb6e',
    storageBucket: 'dbpilot-feb6e.firebasestorage.app',
    androidClientId: '100510560960-iqhr0e1e51l86p829po90q4f20oif5m1.apps.googleusercontent.com',
    iosClientId: '100510560960-8h8bjc0sisvtvehaunrks7b4gl0krlqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.dbpilot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgT-1NyY2dFXyaz3CeruEkFSY9wcu0Odg',
    appId: '1:100510560960:ios:b42c60bd826046d631b325',
    messagingSenderId: '100510560960',
    projectId: 'dbpilot-feb6e',
    storageBucket: 'dbpilot-feb6e.firebasestorage.app',
    androidClientId: '100510560960-iqhr0e1e51l86p829po90q4f20oif5m1.apps.googleusercontent.com',
    iosClientId: '100510560960-8h8bjc0sisvtvehaunrks7b4gl0krlqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.dbpilot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzRe-GY16SLd4ZoF5b_nW38Hfs0XGSmHE',
    appId: '1:100510560960:web:e3bffceaff4c07f531b325',
    messagingSenderId: '100510560960',
    projectId: 'dbpilot-feb6e',
    authDomain: 'dbpilot-feb6e.firebaseapp.com',
    storageBucket: 'dbpilot-feb6e.firebasestorage.app',
  );
}
